/**
 * Where "back to the homepage" goes from inside a generated wiki.
 *
 * A wiki is a static bundle generated by `index`, long before anyone decides
 * which port `codepedia home` will run on - so the link cannot be baked in at
 * generation time. The hub therefore appends its own origin to the URL it
 * navigates to when you open a repository, and this module captures it the same
 * way `apiToken.ts` captures `?token=`: read it once, store it, strip it from
 * the address bar.
 *
 * ## Why only the origin, and never the token
 *
 * `sessionStorage` is scoped per tab *and* per origin, and survives navigating
 * away and back within that tab. So a reader who went hub -> wiki -> hub in one
 * tab still has the hub's own token sitting in the hub's own storage when they
 * arrive back. Carrying the token in this link would widen its exposure - it
 * authorises starting and removing analyses - for no benefit at all.
 *
 * ## Why there is still a fallback
 *
 * A wiki opened by `codepedia serve` directly, or from the filesystem, was
 * never told where the hub is. Pointing at the documented default port is
 * better than offering no way back: if the hub is running there the reader
 * lands on it, and if it is not they get a plain connection error rather than a
 * link that silently does nothing.
 *
 * Nothing here fetches anything. It reads the URL, touches `sessionStorage`,
 * and sets an `href` - so a wiki opened over `file://` stays as fetch-free as
 * it has always been.
 */

const HUB_PARAM = "hub";
const STORAGE_KEY = "codepedia.hubOrigin";

// Matches `DEFAULT_HOME_PORT` in src/cli/main.py. Duplicated deliberately
// rather than plumbed through generation: the wiki is generated before any hub
// exists, so there is nothing to plumb.
const DEFAULT_HUB_URL = "http://127.0.0.1:8100/";

function readStored(): string | null {
  try {
    return window.sessionStorage.getItem(STORAGE_KEY);
  } catch {
    return null;
  }
}

function writeStored(origin: string): void {
  try {
    window.sessionStorage.setItem(STORAGE_KEY, origin);
  } catch {
    // A locked-down profile. The fallback below still gives a usable link.
  }
}

/**
 * Only a loopback http(s) origin is accepted.
 *
 * The value arrives in a URL, and a wiki renders Markdown built from the
 * documented repository - so this is untrusted input in the same sense the
 * rest of the page is. Restricting it to a loopback origin keeps a crafted
 * link from turning the product's own brand into a jump to somewhere else,
 * and rules out `javascript:` outright.
 */
function sanitiseHubOrigin(raw: string): string | null {
  let parsed: URL;
  try {
    parsed = new URL(raw);
  } catch {
    return null;
  }
  if (parsed.protocol !== "http:" && parsed.protocol !== "https:") return null;
  const host = parsed.hostname.replace(/^\[|\]$/g, "");
  if (host !== "127.0.0.1" && host !== "localhost" && host !== "::1") return null;
  return parsed.origin + "/";
}

/**
 * Consume `?hub=` if the hub sent us here. Safe to call more than once.
 */
export function captureHubOriginFromUrl(): void {
  let url: URL;
  try {
    url = new URL(window.location.href);
  } catch {
    return;
  }
  const raw = url.searchParams.get(HUB_PARAM);
  if (!raw) return;

  const origin = sanitiseHubOrigin(raw);
  if (origin) writeStored(origin);

  // Out of the address bar either way, so it is not copied around or kept in
  // history - the same handling `?token=` and `?chatSession=` already get.
  url.searchParams.delete(HUB_PARAM);
  window.history.replaceState(null, "", `${url.pathname}${url.search}${url.hash}`);
}

/** The homepage this wiki should link back to. */
export function hubHomeUrl(): string {
  return readStored() ?? DEFAULT_HUB_URL;
}

/**
 * Point every `[data-hub-home]` anchor at the homepage.
 *
 * Done here rather than in the template because the template is rendered at
 * generation time and cannot know the answer. The `href` those anchors ship
 * with is the wiki's own overview page, so with scripting unavailable they
 * still go somewhere sensible instead of nowhere - the wiki's no-JavaScript
 * behaviour stays intact.
 */
export function installHubHomeLinks(root: ParentNode = document): void {
  const target = hubHomeUrl();
  for (const anchor of Array.from(root.querySelectorAll<HTMLAnchorElement>("a[data-hub-home]"))) {
    anchor.href = target;
  }
}
